### ISSUE TITLE
Application issue

### ISSUE THREAD

**Issue by EdgeCommunications** [RisingTideGroup/cwmanage-dbviewer#1]
Hopefully you can help, because this looks like a slick web app.

I received a database dump from our cloud instance and mounted it on MSSQL.  I installed IIS and I installed php8.2.22 and got all the handler stuff working.  I've successfully connected to the database through the application, but when I click clients, I receive:

PHP Warning:  Undefined variable $title in C:\inetpub\wwwroot\customers.php on line 23

When I go to Tickets, I recveive:

PHP Notice:  session_start(): Ignoring session_start() because a session is already active in C:\inetpub\wwwroot\database.php on line 2

And when I go to projects, I receive:

PHP Notice:  session_start(): Ignoring session_start() because a session is already active in C:\inetpub\wwwroot\database.php on line 2

Any help would be appreciated.  Thanks!

**Comment by greenlighttec** [comment]
None of those are real errors that explain why it snot working, but if you want to reach out to me directly on Reddit, MSPGeek, or Email we can do a remote session to get it working for you @choward420
